import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Leta Pham Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="!scroll-smooth"
    >
      <body
        className={`${inter.className} font-leta  bg-gray-50 text-gray-950`}
      >
        <Navbar />
        <main className="flex flex-col items-center gap-36 px-4 justify-center my-12 tracking-wide">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
